chunk_size: 20
debug: false
distributed:
  batch_size: 50
  enabled: false
  workers:
  - localhost:5000
  - localhost:5001
  - localhost:5002
generate_summary: false
max_history: 5
model:
  concise_responses: true
  max_tokens: 150
  verbosity: low
overlap: 5
parallel:
  batch_size: 10
  max_workers: null
response_mode: concise
temperature: 0.5
