# CodeWhisperer Configuration

# General settings
chunk_size: 20
overlap: 5
max_history: 5
temperature: 0.7
debug: false
generate_summary: false

# Parallel processing settings
parallel:
  max_workers: null  # null means use CPU count
  batch_size: 10    # Number of files to process in a batch for embeddings
  
# Distributed processing settings
distributed:
  enabled: false
  workers:
    - "localhost:5000"  # Example worker address
    - "localhost:5001"
    - "localhost:5002"
  batch_size: 50  # Files per worker batch 